receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'node-exporter'
        scrape_interval: 5s
        static_configs:
        - targets: ['localhost:9100']

processors:

exporters:
  stackdriver:
    project: your-gcp-project
    number_of_workers: 3
    metric:
      # prefix: custom.googleapis.com/opencensus/
      skip_create_descriptor: true
  logging:

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [stackdriver, logging]
